apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  template:
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          args:
            - server
            - /data                         # data directory
            - --address=:9000               # API on 9000
            - --console-address=:9001       # Console on 9001 (ensure it's fixed)
          env:
            - name: MINIO_BROWSER_REDIRECT_URL
              value: "http://minio.istem-lab.com/minio/" 
            - name: MINIO_CONSOLE_SUBPATH
              value: "/minio"
          ports:
            - containerPort: 9000
            - containerPort: 9001
