apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        args:
          - server
          - /data
        env:
          - name: MINIO_ROOT_USER
            valueFrom:
              secretKeyRef:
                name: minio-secret
                key: accesskey
          - name: MINIO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: minio-secret
                key: secretkey
          # Remove MINIO_BROWSER_REDIRECT_URL to avoid the loop
          #- name: MINIO_BROWSER_REDIRECT_URL
          #  value: "http://minio.istem-lab.com"
          - name: MINIO_DOMAIN
            value: "minio.istem-lab.com"
        ports:
          - containerPort: 9000
        volumeMounts:
          - name: minio-data
            mountPath: /data
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-pvc
