apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        args:
          - "server"
          - "/data"
        env:
          - name: MINIO_ROOT_USER
            value: "minioadmin"
          - name: MINIO_ROOT_PASSWORD
            value: "minioadmin"
        ports:
          - containerPort: 9000  # S3 API endpoint
          - containerPort: 9001  # Console endpoint
        volumeMounts:
          - name: minio-data
            mountPath: /data
      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-pvc
