apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2    # enable subpath rewriting
    nginx.ingress.kubernetes.io/proxy-body-size: "0"   # (optional) allow large uploads
spec:
  rules:
  - host: minio.istem-lab.com
    http:
      paths:
        - path: /minio(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: minio-service       # same service as above
              port:
                number: 9001           # console service port
        - path: /
          pathType: Prefix
          backend:
            service:
              name: minio-service
              port:
                number: 80             # API service port
