apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: minio
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-preserve-host: "true"
spec:
  rules:
  - host: minio.istem-lab.com
    http:
      paths:
      - path: /minio(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: minio-service
            port:
              number: 9001
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-service
            port:
              number: 80
  # Uncomment and configure TLS if needed:
  # tls:
  # - hosts:
  #   - minio.istem-lab.com
  #   secretName: minio-tls-secret
