apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio
  labels:
    app: minio
spec:
  type: ClusterIP
  selector:
    app: minio
  ports:
  - name: api
    port: 80
    targetPort: 9000
  - name: console
    port: 9001
    targetPort: 9001
