apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
spec:
  type: ClusterIP
  selector:
    app: minio
  ports:
  - port: 80          # Port exposed to the Ingress
    targetPort: 9000  # Port on which MinIO container listens
    protocol: TCP
