apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
spec:
  selector:
    app: minio
  ports:
  - port: 80         # External port (now standard HTTP)
    targetPort: 9000 # Container port (MinIO listens on 9000)
    protocol: TCP
